In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv(r'D:\udemy\Churn_Modelling.csv')

In [4]:
dataset.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [5]:
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
#Encoding
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x_1=LabelEncoder()
x[:,1]=labelencoder_x_1.fit_transform(x[:,1])
labelencoder_x_2=LabelEncoder()
x[:,2]=labelencoder_x_2.fit_transform(x[:,2])
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()
x=x[:,1:]



C:\Users\rameshsrujana\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [12]:
#SPLITTING
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [13]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
#ANN
import keras
from keras.models import Sequential
from keras.layers import Dense

In [16]:
#initializing ANN
classifier=Sequential()

In [17]:
#Adding input layer and first hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))#relu=rectifier function

C:\Users\rameshsrujana\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [18]:
#adding second hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

C:\Users\rameshsrujana\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [19]:
#Adding the output layer
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

C:\Users\rameshsrujana\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [20]:
#compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [21]:
#Fitting the ANN to training set
classifier.fit(x_train,y_train,batch_size=10,nb_epoch=100)

C:\Users\rameshsrujana\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 4s 562us/step - loss: 0.4930 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4296 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4254 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.4215 - acc: 0.8047
Epoch 5/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.4184 - acc: 0.8234
Epoch 6/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4161 - acc: 0.8271
Epoch 7/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4142 - acc: 0.8285
Epoch 8/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4131 - acc: 0.8297
Epoch 9/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4117 - acc: 0.8310
Epoch 10/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4105 - acc: 0.8327

8000/8000 [==============================] - 1s 136us/step - loss: 0.3993 - acc: 0.8342
Epoch 83/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3992 - acc: 0.8349
Epoch 84/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3992 - acc: 0.8360
Epoch 85/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3993 - acc: 0.8349
Epoch 86/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3992 - acc: 0.8346
Epoch 87/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3992 - acc: 0.8349
Epoch 88/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3996 - acc: 0.8344
Epoch 89/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3990 - acc: 0.8357
Epoch 90/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3987 - acc: 0.8359
Epoch 91/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3993 - acc: 0.8371
Epo

In [22]:
y_pred=classifier.predict(x_test)

In [24]:
len(y_pred)

2000

In [25]:
y_pred=(y_pred>0.5)

In [26]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [27]:
cm

array([[1540,   55],
       [ 252,  153]], dtype=int64)

In [28]:
accuracy=(1540+153)/2000

In [29]:
accuracy

0.8465