In [1]:
import keyword

In [4]:
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [5]:
print(len(keyword.kwlist))

33


In [11]:
class snake:
    def _init_(self,name):
        self.name=name
    def change_name(self,new_name):
        self.name=new_name

In [17]:
cobra=snake("cobra")

TypeError: object() takes no parameters

In [31]:
cities=['mumbai','delhi','hyderabad','chennai']

In [19]:
print(cities)

['mumbai', 'delhi', 'hyderabad', 'chennai']


In [20]:
print('len of list: ',len(cities))

len of list:  4


In [21]:
for i in range(len(cities)):
    print(cities[i])
print('*'*20)
for city in cities:
    print(city)

mumbai
delhi
hyderabad
chennai
********************
mumbai
delhi
hyderabad
chennai


In [24]:
list(range(len(cities)))

[0, 1, 2, 3]

In [25]:
cities.index('mumbai')

0

In [27]:
cities[0]

'mumbai'

In [32]:
print(cities)

['mumbai', 'delhi', 'hyderabad', 'chennai']


In [33]:
cities.pop()

'chennai'

In [34]:
print(cities)

['mumbai', 'delhi', 'hyderabad']


In [36]:
cities.remove('delhi')

In [37]:
print(cities)

['mumbai', 'hyderabad']


In [41]:
a=[5,8,10,12,23,1,2]

In [39]:
a.sort()

In [40]:
a

[1, 2, 5, 8, 10, 12, 23]

In [42]:
sorted(a)

[1, 2, 5, 8, 10, 12, 23]

In [43]:
a

[5, 8, 10, 12, 23, 1, 2]

In [44]:
b=sorted(a)

In [45]:
b

[1, 2, 5, 8, 10, 12, 23]

In [13]:
x=[1,2,3,4,5]

In [2]:
x[:]

[1, 2, 3, 4, 5]

In [3]:
x[1:]

[2, 3, 4, 5]

In [4]:
x[:1]

[1]

In [5]:
x[1:2]

[2]

In [6]:
x[-1]

5

In [7]:
x.append(6)

In [8]:
x

[1, 2, 3, 4, 5, 6]

In [9]:
x.append('srujana')

In [10]:
x

[1, 2, 3, 4, 5, 6, 'srujana']

In [11]:
x.clear()

In [12]:
x

[]

In [14]:
a=x.copy()

In [15]:
a

[1, 2, 3, 4, 5]

In [20]:
x.count(x)

0

In [24]:
x.insert(1,1)

In [25]:
x

[1, 1, 2, 3, 4, 5]

In [26]:
x.insert(4,5)

In [27]:
x

[1, 1, 2, 3, 5, 4, 5]

In [28]:
x.extend([1,2])

In [29]:
x

[1, 1, 2, 3, 5, 4, 5, 1, 2]

In [30]:
x.reverse()

In [31]:
x

[2, 1, 5, 4, 5, 3, 2, 1, 1]

In [32]:
x.sort()

In [33]:
x

[1, 1, 1, 2, 2, 3, 4, 5, 5]

In [34]:
x[0:6:3]

[1, 2]

In [35]:
x.remove(1)

In [36]:
x

[1, 1, 2, 2, 3, 4, 5, 5]

In [39]:
dict={'name':'srujana','college':'njit','place':'newark'}

In [40]:
dict

{'name': 'srujana', 'college': 'njit', 'place': 'newark'}

In [41]:
print(dict)

{'name': 'srujana', 'college': 'njit', 'place': 'newark'}


In [44]:
dict['name']

'srujana'

In [45]:
dict.get('name')

'srujana'

In [46]:
dict.items()

dict_items([('name', 'srujana'), ('college', 'njit'), ('place', 'newark')])

In [49]:
dict.update()

In [50]:
dict

{'name': 'srujana', 'college': 'njit', 'place': 'newark'}

In [51]:
for i in dict.items():
    print(i)

('name', 'srujana')
('college', 'njit')
('place', 'newark')


In [52]:
dict.keys()

dict_keys(['name', 'college', 'place'])

In [53]:
for i in dict.keys():
    print(i)

name
college
place


In [54]:
for i in dict.keys():
    print(dict[i])

srujana
njit
newark


In [58]:
dict1={'colle':'Adams'}

In [59]:
dict.update(dict1)

In [60]:
dict

{'name': 'srujana', 'college': 'Adams', 'place': 'newark', 'colle': 'Adams'}

In [63]:
dict.pop('college')

'Adams'

In [64]:
dict

{'name': 'srujana', 'place': 'newark', 'colle': 'Adams'}

In [1]:
import numpy as np

In [2]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [4]:
print('shape of array :',x.shape)
print('\ntype of array:',type(x))
print('\ndtype of array: ',x.dtype)

shape of array : (2, 2)

type of array: <class 'numpy.ndarray'>

dtype of array:  int32


In [5]:
x=np.array([[1,'srujana'],[2,3]])

In [6]:
x

array([['1', 'srujana'],
       ['2', '3']], dtype='<U11')

In [7]:
x.dtype

dtype('<U11')

In [8]:
type(x)

numpy.ndarray

In [9]:
x.size

4

In [10]:
x.shape

(2, 2)

In [11]:
x.reshape

<function ndarray.reshape>

In [12]:
x

array([['1', 'srujana'],
       ['2', '3']], dtype='<U11')

In [13]:
x.resize

<function ndarray.resize>

In [14]:
x

array([['1', 'srujana'],
       ['2', '3']], dtype='<U11')

In [25]:
a=np.empty(shape=(1,3),dtype=int)
b=np.ones(shape=(1,3),dtype=int)
c=np.zeros(shape=(1,3),dtype=int)

In [37]:
output=np.array([[a,b,c]])

In [38]:
print(output)

[[[[0 0 0]]

  [[1 1 1]]

  [[0 0 0]]]]


In [29]:
w=np.concatenate([a,b,c])

In [33]:
print(w)

[[0 0 0]
 [1 1 1]
 [0 0 0]]


In [30]:
w.shape

(3, 3)

In [31]:
w.size

9

In [39]:
output.shape

(1, 3, 1, 3)

In [40]:
ran=np.arange(start=10,stop=125,step=10,dtype=int)
print(ran)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [41]:
x=np.arange(50,100)
print('original array',x)


original array [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [42]:
x[0]

50

In [46]:
x[49]

99

In [52]:
x[-50:100:2]

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [53]:
x[40:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [56]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [57]:
x=np.array([-1,0,3,4,-3,-9])

In [63]:
print(x[x>0])

[3 4]


In [64]:
y=x[x>=0]

In [65]:
y

array([0, 3, 4])

In [69]:
x=np.random.randint(1,10)

In [72]:
x=np.ones((3,4,5))

In [73]:
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [75]:
x=np.ones((3,4))

In [76]:
x=np.ones([3,4])

In [77]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
x.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [80]:
x.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
y=x.flatten()

In [83]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
z=x.ravel()

In [90]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
x=np.arange(1,10)

In [97]:
x.reshape(3,3,order='C')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
a=x.reshape(3,3,order='F')

In [104]:
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [102]:
a.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.where(x>7)

(array([7, 8], dtype=int64),)

In [123]:
x=np.array([[14,15,16],[7,8,9],[10,1,12]])

In [124]:
x

array([[14, 15, 16],
       [ 7,  8,  9],
       [10,  1, 12]])

In [125]:
x.min()

1

In [119]:
x.max()

16

In [112]:
x.sum()

72

In [113]:
x.mean()

8.0

In [120]:
x.argmax()

2

In [126]:
x.argmin()

7

In [129]:
x[0][1]

15

In [130]:
x[2][2]

12

In [134]:
x

array([[14, 15, 16],
       [ 7,  8,  9],
       [10,  1, 12]])

In [138]:
np.sort(x,axis=0)

array([[ 7,  1,  9],
       [10,  8, 12],
       [14, 15, 16]])

In [139]:
from numpy import random

In [140]:
random.rand(3)

array([0.5858906 , 0.64647737, 0.10973909])

In [141]:
random.randn(3)

array([1.22092866, 0.03724457, 0.29211374])

In [142]:
random.randint(3)

2

In [143]:
random.ranf(3)

array([0.10143529, 0.89318923, 0.37151563])

In [144]:
random.random_integers(3)

C:\Users\rameshsrujana\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  """Entry point for launching an IPython kernel.


2

In [151]:
random.randint(3,10,5)

array([7, 7, 9, 3, 3])

In [152]:
from numpy.random import shuffle

In [155]:
x=np.arange(5)
np.save('x.npy',x)

In [156]:
t=np.load('x.npy')

In [157]:
t

array([0, 1, 2, 3, 4])