## ARITHMETIC OPERATIONS

In [1]:

5+6

11

In [2]:
9-11

-2

In [3]:
9*7

63

In [4]:
8/11

0.7272727272727273

In [5]:
#square
4**4

256

In [6]:
5**2

25

In [7]:
#modulos
90%4

2

In [8]:
'ab'+'cd'

'abcd'

In [10]:
'ab'+'c'

'abc'

In [11]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float

pi_float=float(pi_string)


I started with $100 and now have $194.87171000000012. Awesome!


In [13]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of growth_multiplier and savings to year1
year1=savings*growth_multiplier

# Print the type of year1

print(type(year1))
# Assign sum of desc and desc to doubledesc
doubledesc=desc+desc

# Print out doubledesc
print(doubledesc)

<class 'float'>
compound interestcompound interest


In [14]:
"I said " + ("Hey " * 2) + "Hey!"


'I said Hey Hey Hey!'

In [18]:
q = 0.85196
print(round(q,3))

0.852


In [26]:
a = [4.04, 4.83, 5.44]
b = ['q', 'e', 'j']
c = [9, 8, 3]
print([c,b,a])

[[9, 8, 3], ['q', 'e', 'j'], [4.04, 4.83, 5.44]]


In [27]:
y = "this sentence has no meaning"
print(y.upper())

THIS SENTENCE HAS NO MEANING


In [28]:
import numpy as np
m = np.array([6, 2, 4])
n = np.array([True, False, True])
print(m / n)

[ 6. inf  4.]


C:\Users\rameshsrujana\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [30]:
import numpy as np
x = np.array([4, 1, 19, 7])
print(x[0:3])

[ 4  1 19]


In [31]:
import numpy as np
x = np.array([0, 6, 9, 9, 9])
bool_x = x > 3
print(bool_x)

[False  True  True  True  True]


In [34]:
import numpy as np
x = np.array([6, 6, 4, 4])
y = np.array([6, 4, 0, 4])
print(np.corrcoef(x, y))

[[1.        0.6882472]
 [0.6882472 1.       ]]


In [35]:
[1, 0, 1] + [2, 4, 6]


[1, 0, 1, 2, 4, 6]

In [38]:
x = np.array([3, 4, True, False, 5.2])
print(x)

[3.  4.  1.  0.  5.2]
