In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset=pd.read_csv(r"D:\udemy\Machine Learning A-Z Template Folder\Part 2 - Regression\Section 5 - Multiple Linear Regression\Multiple_Linear_Regression\50_Startups.csv")

In [3]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,4].values

In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x=LabelEncoder()
x[:,3]=labelencoder_x.fit_transform(x[:,3])
onehotencoder=OneHotEncoder(categorical_features=[3])
x=onehotencoder.fit_transform(x).toarray()

C:\Users\rameshsrujana\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [6]:
x

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [7]:
#avoiding the dummy variable trap
x=x[:,1:]

In [8]:
x

array([[0.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 1.4437241e+05, 1.1867185e+05,
        3.8319962e+05],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05],
       [0.0000000e+00, 1.0000000e+00, 1.3187690e+05, 9.9814710e+04,
        3.6286136e+05],
       [0.0000000e+00, 0.0000000e+00, 1.3461546e+05, 1.4719887e+05,
        1.2771682e+05],
       [1.0000000e+00, 0.0000000e+00, 1.3029813e+05, 1.4553006e+05,
        3.2387668e+05],
       [0.0000000e+00, 1.0000000e+00, 1.2054252e+05, 1.4871895e+05,
        3.1161329e+05],
       [0.0000000e+00, 0.0000000e+00, 1.2333488e+05, 1.0867917e+05,
        3.0498162e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0191308e+05, 1.1059411e+05,
        2.29

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
#Fitting multiple linear regression
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [11]:
#Predicting test set results
y_pred=regressor.predict(x_test)

In [12]:
y_pred

array([103015.20159795, 132582.27760817, 132447.73845176,  71976.09851257,
       178537.48221058, 116161.24230165,  67851.69209675,  98791.73374686,
       113969.43533013, 167921.06569553])

In [14]:
import statsmodels.formula.api as sm
x=np.append(arr=np.ones((50,1)).astype(int),values=x,axis=1)
x_opt=x[:,[0,1,2,3,4,5]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     205.0
Date:                Wed, 13 Mar 2019   Prob (F-statistic):           2.90e-28
Time:                        00:45:21   Log-Likelihood:                -526.75
No. Observations:                  50   AIC:                             1064.
Df Residuals:                      45   BIC:                             1073.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        2.73e+04   3185.530      8.571      0.000    2.09e+04    3.37e+04
x1           2.73e+04   3185.530      8.571      0.000    2.09e+04    3.37e+04
x2          1091.1075   3377.087      0.323      0.748   -5710.695    7892.910
x3           -39.3434   3309.047     -0.012      0.991   -6704.106    6625.420
x4             0.8609      0.031     27.665      0.000       0.798       0.924
x5            -0.0527      0.050     -1.045      0.301      -0.154       0.049
==============================================================================
Omnibus:                       14.275   Durbin-Watson:                   1.197
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.260
Skew:                          -0.953   Prob(JB):                     6.57e-05
Kurtosis:                       5.369   Cond. No.                     3.45e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.05e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [15]:
#Remove highest P value predictor 3rd step of multiple linear regression
x_opt=x[:,[0,1,2,4,5]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     279.4
Date:                Wed, 13 Mar 2019   Prob (F-statistic):           1.59e-29
Time:                        00:48:15   Log-Likelihood:                -526.75
No. Observations:                  50   AIC:                             1062.
Df Residuals:                      46   BIC:                             1069.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.729e+04   3060.993      8.917      0.000    2.11e+04    3.35e+04
x1          2.729e+04   3060.993      8.917      0.000    2.11e+04    3.35e+04
x2          1111.1761   2893.049      0.384      0.703   -4712.230    6934.582
x3             0.8609      0.031     28.127      0.000       0.799       0.922
x4            -0.0527      0.050     -1.057      0.296      -0.153       0.048
==============================================================================
Omnibus:                       14.252   Durbin-Watson:                   1.197
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.188
Skew:                          -0.953   Prob(JB):                     6.81e-05
Kurtosis:                       5.362   Cond. No.                     1.16e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.95e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [16]:
x_opt=x[:,[0,1,4,5]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     426.8
Date:                Wed, 13 Mar 2019   Prob (F-statistic):           7.29e-31
Time:                        00:49:39   Log-Likelihood:                -526.83
No. Observations:                  50   AIC:                             1060.
Df Residuals:                      47   BIC:                             1065.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.744e+04   3008.359      9.122      0.000    2.14e+04    3.35e+04
x1          2.744e+04   3008.359      9.122      0.000    2.14e+04    3.35e+04
x2             0.8621      0.030     28.589      0.000       0.801       0.923
x3            -0.0530      0.049     -1.073      0.289      -0.152       0.046
==============================================================================
Omnibus:                       14.678   Durbin-Watson:                   1.189
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.449
Skew:                          -0.961   Prob(JB):                     3.63e-05
Kurtosis:                       5.474   Cond. No.                     1.02e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.04e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [17]:
x_opt=x[:,[0,1,4]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Wed, 13 Mar 2019   Prob (F-statistic):           3.50e-32
Time:                        00:51:06   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.452e+04   1268.948     19.320      0.000     2.2e+04    2.71e+04
x1          2.452e+04   1268.948     19.320      0.000     2.2e+04    2.71e+04
x2             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     2.21e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.67e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [24]:
x_opt

array([[1.0000000e+00, 1.0000000e+00, 1.6534920e+05],
       [1.0000000e+00, 1.0000000e+00, 1.6259770e+05],
       [1.0000000e+00, 1.0000000e+00, 1.5344151e+05],
       [1.0000000e+00, 1.0000000e+00, 1.4437241e+05],
       [1.0000000e+00, 1.0000000e+00, 1.4210734e+05],
       [1.0000000e+00, 1.0000000e+00, 1.3187690e+05],
       [1.0000000e+00, 1.0000000e+00, 1.3461546e+05],
       [1.0000000e+00, 1.0000000e+00, 1.3029813e+05],
       [1.0000000e+00, 1.0000000e+00, 1.2054252e+05],
       [1.0000000e+00, 1.0000000e+00, 1.2333488e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0191308e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0067196e+05],
       [1.0000000e+00, 1.0000000e+00, 9.3863750e+04],
       [1.0000000e+00, 1.0000000e+00, 9.1992390e+04],
       [1.0000000e+00, 1.0000000e+00, 1.1994324e+05],
       [1.0000000e+00, 1.0000000e+00, 1.1452361e+05],
       [1.0000000e+00, 1.0000000e+00, 7.8013110e+04],
       [1.0000000e+00, 1.0000000e+00, 9.4657160e+04],
       [1.0000000e+00, 1.000

In [20]:
#Automatic Backward Elimination with p-values only:

import statsmodels.formula.api as sm
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x
 


In [22]:
SL = 0.05
X_opt = x[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)



In [23]:
X_Modeled

array([[1.0000000e+00, 1.0000000e+00, 1.6534920e+05],
       [1.0000000e+00, 1.0000000e+00, 1.6259770e+05],
       [1.0000000e+00, 1.0000000e+00, 1.5344151e+05],
       [1.0000000e+00, 1.0000000e+00, 1.4437241e+05],
       [1.0000000e+00, 1.0000000e+00, 1.4210734e+05],
       [1.0000000e+00, 1.0000000e+00, 1.3187690e+05],
       [1.0000000e+00, 1.0000000e+00, 1.3461546e+05],
       [1.0000000e+00, 1.0000000e+00, 1.3029813e+05],
       [1.0000000e+00, 1.0000000e+00, 1.2054252e+05],
       [1.0000000e+00, 1.0000000e+00, 1.2333488e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0191308e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0067196e+05],
       [1.0000000e+00, 1.0000000e+00, 9.3863750e+04],
       [1.0000000e+00, 1.0000000e+00, 9.1992390e+04],
       [1.0000000e+00, 1.0000000e+00, 1.1994324e+05],
       [1.0000000e+00, 1.0000000e+00, 1.1452361e+05],
       [1.0000000e+00, 1.0000000e+00, 7.8013110e+04],
       [1.0000000e+00, 1.0000000e+00, 9.4657160e+04],
       [1.0000000e+00, 1.000

In [25]:
import statsmodels.formula.api as sm
def backwardElimination(x, SL):
    numVars = len(x[0])
    temp = np.zeros((50,6)).astype(int)
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        adjR_before = regressor_OLS.rsquared_adj.astype(float)
        if maxVar > SL:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    temp[:,j] = x[:, j]
                    x = np.delete(x, j, 1)
                    tmp_regressor = sm.OLS(y, x).fit()
                    adjR_after = tmp_regressor.rsquared_adj.astype(float)
                    if (adjR_before >= adjR_after):
                        x_rollback = np.hstack((x, temp[:,[0,j]]))
                        x_rollback = np.delete(x_rollback, j, 1)
                        print (regressor_OLS.summary())
                        return x_rollback
                    else:
                        continue
    regressor_OLS.summary()
    return x
 

In [26]:

SL = 0.05
X_opt = x[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     426.8
Date:                Wed, 13 Mar 2019   Prob (F-statistic):           7.29e-31
Time:                        01:11:41   Log-Likelihood:                -526.83
No. Observations:                  50   AIC:                             1060.
Df Residuals:                      47   BIC:                             1065.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.744e+04   3008.359      9.122      0.0

In [27]:
X_Modeled

array([[1.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689700e+05],
       [1.0000000e+00, 1.0000000e+00, 1.6259770e+05, 1.5137700e+05],
       [1.0000000e+00, 1.0000000e+00, 1.5344151e+05, 1.0114500e+05],
       [1.0000000e+00, 1.0000000e+00, 1.4437241e+05, 1.1867100e+05],
       [1.0000000e+00, 1.0000000e+00, 1.4210734e+05, 9.1391000e+04],
       [1.0000000e+00, 1.0000000e+00, 1.3187690e+05, 9.9814000e+04],
       [1.0000000e+00, 1.0000000e+00, 1.3461546e+05, 1.4719800e+05],
       [1.0000000e+00, 1.0000000e+00, 1.3029813e+05, 1.4553000e+05],
       [1.0000000e+00, 1.0000000e+00, 1.2054252e+05, 1.4871800e+05],
       [1.0000000e+00, 1.0000000e+00, 1.2333488e+05, 1.0867900e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0191308e+05, 1.1059400e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0067196e+05, 9.1790000e+04],
       [1.0000000e+00, 1.0000000e+00, 9.3863750e+04, 1.2732000e+05],
       [1.0000000e+00, 1.0000000e+00, 9.1992390e+04, 1.3549500e+05],
       [1.0000000e+00, 1.0000000e+