In [5]:
import numpy as np

In [12]:
x=np.empty(shape=[2,2],dtype = int)
print(x)

[[4980803 4456533]
 [3997765 3801155]]


In [16]:
zero=np.zeros([3,3],dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
one=np.ones([3,4],dtype=int)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
arang=np.arange(100,200,10)
print(arang)

[100 110 120 130 140 150 160 170 180 190]


In [22]:
basic=np.arange(1,10)
print(basic)

[1 2 3 4 5 6 7 8 9]


In [23]:
basic[4]

5

In [24]:
basic[-9:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
boolean=np.array([1,-2.0,1.2,-10,5,6])
print(boolean)

[  1.   -2.    1.2 -10.    5.    6. ]


In [28]:
print(boolean>0)

[ True False  True False  True  True]


In [29]:
print(boolean[boolean>0])

[1.  1.2 5.  6. ]


In [34]:
manipulating=np.ones((3,4))
print(manipulating)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
manipulating.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
#flatten collapses the array into one direction

In [36]:
manipulating.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
manipulating.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
manipulating.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
#hstack
#stack arrays hprizantally
#should have same n.o of rows

In [43]:
x=np.ones((2,3))
y=np.zeros((2,2))
z=np.hstack((x,y))

In [44]:
print(z)

[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


In [46]:
x=np.ones((2,2))
y=np.zeros((1,2))
z=np.vstack((x,y))

In [47]:
print(z)

[[1. 1.]
 [1. 1.]
 [0. 0.]]


In [51]:
x=[0,1,2]
y=['x','y','z']
hst=np.hstack((x,y))
vst=np.vstack((x,y))
print('hst is:',hst)
print('vst is: ',vst)

hst is: ['0' '1' '2' 'x' 'y' 'z']
vst is:  [['0' '1' '2']
 ['x' 'y' 'z']]


In [52]:
np.where(z>0)

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [55]:
x=np.arange(3,10)

In [56]:
x

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
np.where(x>7)

(array([5, 6], dtype=int64),)

In [58]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [59]:
np.cumsum(x)

array([ 3,  7, 12, 18, 25, 33, 42], dtype=int32)

In [63]:
a=np.array([[0,1,2],[0,1,0],[0,0,0],[0,1,2]])
print(a)

[[0 1 2]
 [0 1 0]
 [0 0 0]
 [0 1 2]]


In [64]:
np.unique(a,axis=0)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 1, 2]])

In [69]:
print(np.unique(a,axis=1))
len(np.unique(a,axis=1))

[[0 1 2]
 [0 1 0]
 [0 0 0]
 [0 1 2]]


4

In [67]:
len(np.unique(a))

3

In [71]:
arith=np.array([[4,5,6],[1,2,3],[0,1,0]])

In [72]:
arith.sum()

22

In [73]:
arith.min()

0

In [74]:
arith.max()

6

In [75]:
arith.mean()

2.4444444444444446

In [76]:
arith.argmin()

6

In [77]:
arith.argmax()

2

In [78]:
#random numbers
from numpy import random

In [84]:
np.random.seed(5)
x=np.random.rand(5)
print(x)

[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]


In [83]:
print(random.randint(3,10,6))

[9 6 3 9 3 7]


In [91]:
c=np.arange(10)
print(c)


[0 1 2 3 4 5 6 7 8 9]


In [92]:
from numpy.random import shuffle

In [93]:
shuffle(c)

In [94]:
print(c)

[0 5 6 7 1 9 2 8 3 4]


In [95]:
np.save('numpy.npy',c)

In [96]:
numpy=np.load('numpy.npy')

In [97]:
numpy

array([0, 5, 6, 7, 1, 9, 2, 8, 3, 4])

In [98]:
a=np.array([1,2,3,4,2,3,4])
print(a)
print(np.unique(a))

[1 2 3 4 2 3 4]
[1 2 3 4]


In [100]:
#check if one array is in another
a=np.array([1,2,4])
b=np.arange(3)
np.in1d(a,b)

array([ True,  True, False])

In [101]:
np.intersect1d(a,b)

array([1, 2])

In [102]:
np.union1d(a,b)

array([0, 1, 2, 4])

In [103]:
np.setdiff1d(a,b)

array([4])

In [104]:
np.setdiff1d(b,a)

array([0])

In [105]:
np.setxor1d(a,b)

array([0, 4])