In [2]:
import numpy as  np


In [4]:
#array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
#matrix
m1=[[10,11,15,14],[1,2,3,4],[7,8,9,10]]

In [7]:
m1

[[10, 11, 15, 14], [1, 2, 3, 4], [7, 8, 9, 10]]

In [8]:
print(m1)

[[10, 11, 15, 14], [1, 2, 3, 4], [7, 8, 9, 10]]


In [10]:
np.array([[10,11,15,14],[1,2,3,4],[7,8,9,10]])

array([[10, 11, 15, 14],
       [ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [11]:
np.random.rand(5)

array([0.31376771, 0.25081655, 0.24463416, 0.97608261, 0.93326797])

In [13]:
np.random.rand(4)#uniform distribution

array([0.49681518, 0.22070446, 0.27315323, 0.56885632])

In [14]:
np.random.rand(4,4)

array([[0.94980124, 0.37235222, 0.88792453, 0.43727746],
       [0.13979928, 0.15933274, 0.9292163 , 0.60505524],
       [0.42567812, 0.73873725, 0.83825927, 0.61744977],
       [0.41211225, 0.68519957, 0.1413916 , 0.24604192]])

In [16]:
np.random.rand(2)

array([0.19793504, 0.49610788])

In [17]:
np.random.randint(1,10)

2

In [18]:
np.random.randint(1,50,5)

array([43,  8, 43, 19, 12])

In [20]:
np.random.randint(1)

0

In [21]:
np.random.randint(1,10,10)

array([6, 3, 3, 6, 6, 9, 2, 9, 1, 4])

In [23]:
np.random.randint(4,10,2)

array([5, 9])

In [24]:
x=np.random.randint(1,50,6)

In [25]:
x

array([16, 18, 18, 19, 21, 46])

In [26]:
x.reshape(2,3)

array([[16, 18, 18],
       [19, 21, 46]])

In [28]:
x.reshape(3,2)

array([[16, 18],
       [18, 19],
       [21, 46]])

In [29]:
x.max()

46

In [30]:
x.min()

16

In [32]:
x.argmax()

5

In [33]:
x.argmin()

0

In [35]:
x.shape

(6,)

In [36]:
y=x.reshape(2,3)

In [38]:
y.shape

(2, 3)

In [39]:
x.sum()

138

In [40]:
y.sum()

138

In [42]:
a=np.array([[2,3],[4,5]])

In [43]:
b=np.array([[1,2]])

In [44]:
a
b

array([[1, 2]])

In [45]:
a

array([[2, 3],
       [4, 5]])

In [46]:
np.concatenate((a,b),axis=0)# by rows

array([[2, 3],
       [4, 5],
       [1, 2]])

In [47]:
np.concatenate((a,b),axis=0).shape

(3, 2)

In [48]:
np.concatenate((a,b),axis=1)# error due to columns

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [50]:
b.T#transpose

array([[1],
       [2]])

In [51]:
b.shape

(1, 2)

In [52]:
np.concatenate((a,b.T),axis=1)#transpose and column wise

array([[2, 3, 1],
       [4, 5, 2]])

In [55]:
np.concatenate((a,b),axis=None)#no rows no columns

array([2, 3, 4, 5, 1, 2])

In [56]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3])
a3=np.array([1,2])

In [57]:
np.concatenate((a1,a2,a3),axis=None)

array([1, 2, 3, 4, 1, 2, 3, 1, 2])