In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import os
os.chdir('D:\marlabs\Datasets\santander')

In [6]:
dataset=pd.read_csv(r'train.csv')

In [39]:
dataset['target'].unique()

array([0, 1], dtype=int64)

In [10]:
x=dataset.iloc[:,2:].values
y=dataset.iloc[:,1].values

In [26]:
y[4]

0

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [30]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x,y,test_size=0.20,random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [31]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train1=sc.fit_transform(x_train1)
x_test1=sc.transform(x_test1)

In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [32]:

from xgboost import XGBClassifier
classifier=XGBClassifier()
classifier.fit(x_train1,y_train1)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [18]:
y_pred=classifier.predict(x_test)

In [33]:
y_pred1=classifier.predict(x_train1)

In [34]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train1,y_pred1)

In [35]:
cm

array([[35980,     6],
       [ 3949,    65]], dtype=int64)

In [36]:
acc=(35980+65)/40000

In [37]:
acc

0.901125

In [23]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
from xgboost import XGBClassifier
classifier=XGBClassifier()
classifier.fit(x_train1,y_train1)

In [38]:
#applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=x_train1,y=y_train1,cv=10)
accuracies.mean()
accuracies.std()

0.000339413033170958