In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('D:\marlabs\Datasets\iris.csv')

In [3]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [4]:
df.columns=['sepal_length','sepal_width','petal_length','petal_width','target']

In [5]:
x=df.drop('target',axis=1)

In [6]:
y=df['target'].apply(int)

In [7]:
y.unique()

array([0, 1, 2], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [10]:
#Estimators

In [11]:
import tensorflow as tf

In [12]:
x.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [14]:
feat_cols=[]
for col in x.columns:
    feat_cols.append(tf.feature_column.numeric_column(col))
    

In [15]:
feat_cols


[_NumericColumn(key='sepal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sepal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [16]:
input_func=tf.estimator.inputs.pandas_input_fn(x=x_train,y=y_train,batch_size=10,num_epochs=5,shuffle=True)

In [17]:
classifier=tf.estimator.DNNClassifier(hidden_units=[10,20,10],n_classes=3,feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\RAMESH~1\\AppData\\Local\\Temp\\tmprt7khewy', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}


In [18]:
classifier.train(input_fn=input_func,steps=50)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\RAMESH~1\AppData\Local\Temp\tmprt7khewy\model.ckpt.
INFO:tensorflow:loss = 10.069707, step = 1
INFO:tensorflow:Saving checkpoints for 50 into C:\Users\RAMESH~1\AppData\Local\Temp\tmprt7khewy\model.ckpt.
INFO:tensorflow:Loss for final step: 1.0074309.


In [19]:
#Model Evaluation
pred_fn=tf.estimator.inputs.pandas_input_fn(x=x_test,batch_size=len(x_test),shuffle=False)

In [20]:
note_predictions=list(classifier.predict(input_fn=pred_fn))

INFO:tensorflow:Restoring parameters from C:\Users\RAMESH~1\AppData\Local\Temp\tmprt7khewy\model.ckpt-50


In [21]:
classifier.predict(input_fn=pred_fn)

<generator object Estimator.predict at 0x00000025B10B2308>

In [22]:
note_predictions

[{'logits': array([-6.395413  , -1.3692952 ,  0.90701556], dtype=float32),
  'probabilities': array([6.1078428e-04, 9.3047112e-02, 9.0634215e-01], dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-3.245899 , -0.3926689, -1.4833515], dtype=float32),
  'probabilities': array([0.04137193, 0.7175429 , 0.24108514], dtype=float32),
  'class_ids': array([1], dtype=int64),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ 3.5569043, -0.8175789, -6.273826 ], dtype=float32),
  'probabilities': array([9.8750955e-01, 1.2437338e-02, 5.3101809e-05], dtype=float32),
  'class_ids': array([0], dtype=int64),
  'classes': array([b'0'], dtype=object)},
 {'logits': array([-7.5943594, -1.6269284,  1.0541668], dtype=float32),
  'probabilities': array([1.6411634e-04, 6.4087637e-02, 9.3574828e-01], dtype=float32),
  'class_ids': array([2], dtype=int64),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-8.727936 , -2.

In [23]:
note_predictions[0]

{'logits': array([-6.395413  , -1.3692952 ,  0.90701556], dtype=float32),
 'probabilities': array([6.1078428e-04, 9.3047112e-02, 9.0634215e-01], dtype=float32),
 'class_ids': array([2], dtype=int64),
 'classes': array([b'2'], dtype=object)}

In [24]:
note_predictions[0]['class_ids'][0]

2

In [25]:
final_preds=[]
for pred in note_predictions:
    final_preds.append(pred['class_ids'][0])

In [26]:
final_preds

[2,
 1,
 0,
 2,
 2,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 0,
 1,
 0]

In [27]:
from sklearn.metrics import confusion_matrix,classification_report


In [28]:
print(confusion_matrix(y_test,final_preds))

[[16  0  0]
 [ 0 10  5]
 [ 0  0 14]]


In [29]:
print(classification_report(y_test,final_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.67      0.80        15
           2       0.74      1.00      0.85        14

   micro avg       0.89      0.89      0.89        45
   macro avg       0.91      0.89      0.88        45
weighted avg       0.92      0.89      0.89        45

