In [1]:
c=15


In [2]:
print(c)

15


In [3]:
print("c is:" ,c)

c is: 15


In [4]:
import math
math.sqrt(c)

3.872983346207417

In [5]:
round(math.sqrt(c))

4

In [6]:
round(math.sqrt(c),2)

3.87

In [7]:
round(math.sqrt(c),3)

3.873

In [8]:
message='hi'+"  "+'how' +' r '+'u'

In [9]:
message

'hi  how r u'

In [10]:
4<5

True

In [11]:
5>c

False

In [12]:
4!=5

True

In [13]:
4<=5

True

In [14]:
not(5>1)

False

In [15]:
True and False

False

In [16]:
True and True

True

WHILE LOOP

In [17]:
x=1
while x<5:
    print(x)
    x=x+1

1
2
3
4


In [18]:
counter=1
while counter<10:
    print('Hello')
    counter=counter+1

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [19]:
range(5)

range(0, 5)

In [20]:
for i in range(0,5):
    print("Hello")

Hello
Hello
Hello
Hello
Hello


In [21]:
import numpy as np
from numpy.random import randn

In [22]:
randn()

-0.732300044736337

In [23]:
randn(4)

array([-1.43437956, -0.20675792, -0.84128158,  0.78811332])

In [24]:
randn(5,10)

array([[ 1.8455739 , -0.03356663,  0.02177845, -0.96553785,  2.08009881,
        -1.61196823,  2.33830237,  0.7682654 , -0.36590012, -1.15293932],
       [-0.39654241, -0.16094417, -0.70755706,  0.31884278,  0.34451161,
         1.48042533, -0.24986445,  1.31074774, -0.08970875, -0.37369154],
       [ 0.01256642,  0.65561745,  0.34093619,  2.19815335, -0.04721526,
        -0.64459197, -0.08165748,  1.51431187, -0.74607469, -0.76534372],
       [ 0.92381898,  0.00366294,  1.97061376,  0.03656167,  0.91648583,
         1.91351509, -0.39308864,  0.72820094, -1.8077617 ,  0.49709533],
       [ 1.00584226,  0.19957238,  0.73627561, -1.61841793,  1.92016444,
        -0.21007714,  1.7307197 ,  1.66873519,  2.49836907, -1.20614088]])

In [25]:
randn(1,2,3)

array([[[-0.91129128,  0.79110246,  0.52594746],
        [ 3.07602928, -1.41477863,  1.04284241]]])

In [26]:
N=100
counter=0
for i in randn(N):
    if(i<1 and i>-1):
        counter=counter+1
answer=counter/N
print(answer)

0.72


In [27]:
list=[2,49,35,100]

In [28]:
list

[2, 49, 35, 100]

In [29]:
list[0]

2

In [30]:
l1=[23,4,2]

In [31]:
list1=[1.2,list,l1]

In [32]:
list1

[1.2, [2, 49, 35, 100], [23, 4, 2]]

In [33]:
list1[1][2]

35

In [37]:
l=range(10,20)

In [40]:
l=range(5)

In [1]:
range(5)

range(0, 5)

In [2]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [4]:
list(range(1,8))

[1, 2, 3, 4, 5, 6, 7]

In [5]:
x=range(1,5)

In [6]:
x

range(1, 5)

In [7]:
list(range(1,9,2))

[1, 3, 5, 7]

In [17]:
w=list(range(30,301,25))

In [12]:
len(x)

4

In [13]:
x[0]

1

In [14]:
x[-4]

1

In [18]:
w[2]=4

In [19]:
w

[30, 55, 4, 105, 130, 155, 180, 205, 230, 255, 280]

In [20]:
letters=['a','b','c','d','e','f','g','h','i','j']

In [21]:
letters[:]

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [23]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [25]:
letters[0:9]

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

In [27]:
letters[-8:-1]

['c', 'd', 'e', 'f', 'g', 'h', 'i']

In [34]:
letters[-5:0]

[]

In [36]:
letters[1:-1:2]

['b', 'd', 'f', 'h']

In [37]:
letters[1:-1:3]

['b', 'e', 'h']

In [39]:
letters[3:]

['d', 'e', 'f', 'g', 'h', 'i', 'j']

In [40]:
letters[:-3]

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [41]:
letters[::3]

['a', 'd', 'g', 'j']

In [43]:
letters[::-1]

['j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [44]:
letters[::-2]

['j', 'h', 'f', 'd', 'b']

In [45]:
letters[2:7:-1]

[]

In [46]:
letters[7:2:-1]

['h', 'g', 'f', 'e', 'd']

In [47]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [48]:
letters[6:0:-2]

['g', 'e', 'c']

In [49]:
#tuples


In [50]:
x=(1,2,3)

In [51]:
x

(1, 2, 3)

In [52]:
type(x)

tuple

In [53]:
x[0]

1

In [55]:
mylist=list(range(20,31))

In [56]:
print(mylist)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [57]:
len(mylist)

11

In [58]:
min(mylist)

20

In [59]:
max(mylist)

30

In [60]:
sum(mylist)

275

In [64]:
(mylist)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [74]:
import numpy as np
array=np.array(mylist)

In [75]:
array

array(['hello', '21', '22', '23', '24', '25', '26', '27', '28', '29',
       '30'], dtype='<U5')

In [72]:
mylist[0]='hello'

In [73]:
mylist

['hello', 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [78]:
b=np.array([2,3,4.5])

In [79]:
b

array([2. , 3. , 4.5])

In [80]:
b=mylist[0:2]

In [81]:
b

['hello', 21]

In [82]:
mylist

['hello', 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [83]:
b[0]=1

In [84]:
b

[1, 21]

In [85]:
mylist

['hello', 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]